---
title: "Introduction"
author: "Mikkel Meyer Andersen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  echo = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 5
)
```

```{r}
library(tidyverse)
library(kinship2)
library(malan)
#library(copape)
devtools::load_all(".")
```

```{r}
pedid_to_merge <- 7
test_males %>% 
  filter(paternalped_id == pedid_to_merge)
```

```{r}
ped_raw <- test_males %>% 
  filter(paternalped_id == pedid_to_merge) %>% 
  insert_missing_pids()


label <- ped_raw %>% 
  mutate(pid_chr = ifelse(is.na(birthyear), 
                          paste0("(", pid, ")"),
                          paste0(birthyear, "\n", "(", pid, ")"))) %>% 
  pull(pid_chr)

ped <- with(ped_raw, pedigree(id = pid, 
                              dadid = pid_dad, 
                              momid = pid_mom, 
                              sex = sex,
                              status = status))

plot.pedigree(ped, cex = 0.5, id = label)
```


# Take 1

```{r}
set.seed(1)
res <- merge_pedigree(
  pids = dplyr::pull(test_males, pid),
  pids_dad = dplyr::pull(test_males, pid_dad),  
  birthyears = dplyr::pull(test_males, birthyear), 
  paternalped_ids = dplyr::pull(test_males, paternalped_id),
  pedid_to_merge = pedid_to_merge,
  sons_configs = test_sons_configs,
  no_surrogate_ancestors = 2,
  stop_birthyear = 1980,
  force_surrogate_previous_to = 1980,
  surr_pid_start = 5000,
  verbose = FALSE)
res
```

```{r}
pids_in_ped_merge <- test_males %>% 
  filter(paternalped_id == pedid_to_merge) %>% 
  pull(pid)
visualise_merges(res, highlight_pids1 = pids_in_ped_merge, cex = 0.1)
```

```{r}
ped_raw <- res %>% 
  insert_missing_pids()

label <- ped_raw %>% 
  mutate(pid_chr = ifelse(is.na(birthyear), 
                          paste0("(", pid, ")"),
                          paste0(birthyear, "\n", "(", pid, ")",
                                 ifelse(is_surrogate, "\nSURR", "")))) %>% 
  pull(pid_chr)
clr <- ped_raw %>% 
  mutate(clr = case_when(
    sex == "female" ~ "lightgrey",
    is_surrogate ~ "red",
    TRUE ~ "blue")) %>% 
  pull(clr)

ped <- with(ped_raw, pedigree(id = pid, 
                              dadid = pid_dad, 
                              momid = pid_mom, 
                              sex = sex,
                              status = status))

plot.pedigree(ped, cex = 0.5, id = label, col = clr)
```

```{r}
d_old_peds <- res %>% 
  filter(is_surrogate == FALSE) %>% 
  left_join(test_males %>% select(pid, paternalped_id),
            by = "pid")
d_old_peds
d_old_peds %>% 
  group_by(paternalped_id) %>% 
  summarise(n = length(pid),
            pids = paste0(pid, collapse = ", "))
```


# Additional takes

```{r}
set.seed(2)

res_lst <- lapply(1:10, function(i) { 
  merge_pedigree(
    pids = dplyr::pull(test_males, pid),
    pids_dad = dplyr::pull(test_males, pid_dad),  
    birthyears = dplyr::pull(test_males, birthyear), 
    paternalped_ids = dplyr::pull(test_males, paternalped_id),
    pedid_to_merge = pedid_to_merge,
    sons_configs = test_sons_configs,
    no_surrogate_ancestors = 3,
    stop_birthyear = 1980,
    surr_pid_start = 5000,
    verbose = FALSE)
})
```

```{r}
for (res in res_lst) {
  visualise_merges(res)
}
```


