---
title: "Introduction"
author: "Mikkel Meyer Andersen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  comment = "#>",
  fig.width = 8,
  fig.height = 5
)
```

```{r}
library(tidyverse)
library(igraph)
library(ggraph)
library(kinship2)
library(malan)
#library(copape)
devtools::load_all(".")
```

```{r}
pedid_to_merge <- 38
test_males %>% 
  filter(paternalped_id == pedid_to_merge)
```

```{r}
ped_raw <- test_males %>% 
  filter(paternalped_id == pedid_to_merge) %>% 
  insert_missing_pids()
ped_raw

label <- ped_raw %>% 
  mutate(pid_chr = ifelse(is.na(birthyear), 
                          paste0("(", pid, ")"),
                          paste0(birthyear, "\n", "(", pid, ")"))) %>% 
  pull(pid_chr)

ped <- with(ped_raw, pedigree(id = pid, 
                              dadid = pid_dad, 
                              momid = pid_mom, 
                              sex = sex,
                              status = status))

plot.pedigree(ped, cex = 0.5, id = label)
```

```{r}
el_raw <- test_males %>% 
  filter(paternalped_id == pedid_to_merge) %>% 
  add_dad_birthyear() %>% 
  mutate(pid_chr = paste0(birthyear, "\n", "(", pid, ")"),
         pid_dad_chr = paste0(birthyear_dad, "\n", "(", pid_dad, ")"))
el_raw

el <- el_raw %>% 
  filter(!is.na(pid_dad)) %>% 
  select(pid_dad_chr, pid_chr) %>% 
  as.matrix()
el

g <- igraph::graph_from_edgelist(el, directed = TRUE)
ggraph(g, layout = "graphopt") + 
  geom_edge_link(aes(start_cap = label_rect(node1.name),
                     end_cap = label_rect(node2.name)), 
                 arrow = arrow(length = unit(4, 'mm'))) + 
  geom_node_text(aes(label = name)) +
  theme_graph()
```


```{r}
set.seed(1)
res <- merge_pedigree(
  pids = dplyr::pull(test_males, pid),
  pids_dad = dplyr::pull(test_males, pid_dad),  
  birthyears = dplyr::pull(test_males, birthyear), 
  paternalped_ids = dplyr::pull(test_males, paternalped_id),
  pedid_to_merge = pedid_to_merge,
  sons_configs = test_sons_configs,
  no_surrogate_ancestors = 3,
  stop_birthyear = 1970,
  surr_pid_start = 50000000,
  verbose = FALSE)
res
```

```{r}
ped_raw <- res %>% 
  insert_missing_pids()
ped_raw

label <- ped_raw %>% 
  mutate(pid_chr = ifelse(is.na(birthyear), 
                          paste0("(", pid, ")"),
                          paste0(birthyear, "\n", "(", pid, ")",
                                 ifelse(is_surrogate, "\nSURR", "")))) %>% 
  pull(pid_chr)

ped <- with(ped_raw, pedigree(id = pid, 
                              dadid = pid_dad, 
                              momid = pid_mom, 
                              sex = sex,
                              status = status))

plot.pedigree(ped, cex = 0.5, id = label)
```


```{r}
el_raw <- res %>% 
  add_dad_birthyear() %>% 
  add_dad_is_surrogate() %>% 
  mutate(pid_chr = paste0(birthyear, #"\n", "(", pid, ")", 
                          ifelse(is_surrogate, "\nSURR", "")),
         pid_dad_chr = paste0(birthyear_dad, #"\n", "(", pid_dad, ")", 
                              ifelse(is_surrogate_dad, "\nSURR", "")))
el_raw


el <- el_raw %>% 
  filter(!is.na(pid_dad)) %>% 
  select(pid_dad_chr, pid_chr) %>% 
  as.matrix()
el

g <- igraph::graph_from_edgelist(el, directed = TRUE)
```

```{r, fig.out = 10, fig.height=10}
ggraph(g, layout = "kk", maxiter = 5000) + 
  geom_edge_link(aes(start_cap = label_rect(node1.name),
                     end_cap = label_rect(node2.name)), 
                 arrow = arrow(length = unit(4, 'mm'))) + 
  geom_node_text(aes(label = name)) +
  theme_graph()
```


