# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Merge a pedigree randomly
#' 
#' Note that children will be added according to `sons_configs`.
#' 
#' @inheritParams validate_merge_input
#' @inheritParams validate_surr_pid_start
#' @inheritParams validate_sons_configs
#' @param pedid_to_merge id of pedigree that will be merged with other pedigrees
#' @param no_surrogate_ancestors number of surrogate ancestors to add
#' @param verbose verbose output
#' 
#' @return Only individuals in new pedigree.
#' 
#' @export
merge_pedigree <- function(pids, pids_dad, birthyears, paternalped_ids, pedid_to_merge, sons_configs, no_surrogate_ancestors = 1L, stop_birthyear = 1970L, surr_pid_start = 50000000L, verbose = FALSE) {
    .Call('_copape_merge_pedigree', PACKAGE = 'copape', pids, pids_dad, birthyears, paternalped_ids, pedid_to_merge, sons_configs, no_surrogate_ancestors, stop_birthyear, surr_pid_start, verbose)
}

#' Validate merge input
#' 
#' @param pids vector of person ids: >= 1 (`NA` not allowed)
#' @param pids_dad vector of person ids for dad: >= 1 (`NA` for founders)
#' @param birthyears vector of birth years: free
#' @param paternalped_ids vector of pedigree ids: >= 1 (`NA` not allowed)
#' 
validate_merge_input <- function(pids, pids_dad, birthyears, paternalped_ids) {
    invisible(.Call('_copape_validate_merge_input', PACKAGE = 'copape', pids, pids_dad, birthyears, paternalped_ids))
}

#' Validate surrogate father id input
#' 
#' @param pids person id: >= 1 (`NA` not allowed)
#' @param surr_pid_start start person id for new surrogate individuals
#' 
validate_surr_pid_start <- function(pids, surr_pid_start) {
    invisible(.Call('_copape_validate_surr_pid_start', PACKAGE = 'copape', pids, surr_pid_start))
}

#' Validate configuration of sons (age of father when each son is born)
#' 
#' @param sons_configs list of sons (age of father when each son was born); 
#' elements cannot be of size 0 and all ages be > 0. E.g. `list(c(28, 30), c(24))`.
#' 
validate_sons_configs <- function(sons_configs) {
    invisible(.Call('_copape_validate_sons_configs', PACKAGE = 'copape', sons_configs))
}

#' Random index between 0 and n-1 (both included)
#' 
#' @param n upper limit (not included)
random_index <- function(n) {
    .Call('_copape_random_index', PACKAGE = 'copape', n)
}

